//{$DEFINE SELFPROTECT}

//{$DEFINE PROTECTANTIFLOOD}

{.$DEFINE UNICODERSNET} // при активации выбор истории осуществляется стрелками "вверх"-"вниз"

{.$DEFINE ADMINPACK} // Включает функции администрирования чата (необходимо сделать видимым пункты меню в pmUser)

{.$DEFINE ANTI_ADMINPACK} // Позволяет заблокировать действия админпаков на чат

{.$DEFINE NOENTEREXIT} //    Отключает события вход-выход в чат (маскировка)

{.$DEFINE ADMINCHAT} // Special features